font_family                    JetBrainsMono Nerd Font
font_size                      14.0
background_opacity             0.85
disable_ligatures              no
enable_audio_bell              no
shell                          zsh
url_style                      curly
window_padding_width           20
cursor_shape                   block
cursor_blink_interval          0.5
confirm_os_window_close        0

background #20113d
foreground #e0e0e0

active_border_color #3e2473
inactive_border_color #2d1659

color0 #20113d
color8 #4a3070

color1 #e62828
color9 #ff2a2a

color2 #76ff03
color10 #8eff3b

color3 #ffbb00
color11 #ffd500

color4 #3e2473
color12 #8a5ef0

color5 #8a5ef0
color13 #b59bff
color6 #8b9dc3
color14 #a8bce6

color7 #e0e0e0
color15 #ffffff

cursor #76ff03