font_family                    JetBrainsMono Nerd Font
font_size                      14.0
background_opacity             0.85
disable_ligatures              no
enable_audio_bell              no
shell                          zsh
url_style                      curly
window_padding_width           20
cursor_shape                   block
cursor_blink_interval          0.5
confirm_os_window_close        0

background #150909
foreground #f2e6e6

active_border_color #e62828
inactive_border_color #4a1c1c

color0 #1a0f0f
color8 #4a2c2c

color1 #d62828
color9 #ff3333

color2 #4caf50
color10 #76d275

color3 #ff8800
color11 #ffaa00

color4 #1d4e89
color12 #3a7ca5

color5 #c71585
color13 #ff66cc

color6 #20b2aa
color14 #48d1cc

color7 #e0e0e0
color15 #ffffff

cursor #ff8800